# Generated by Django 4.1.9 on 2025-06-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('spatk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('spdef', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
